# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-09-07 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200904_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='articledetail',
            name='content',
            field=models.TextField(default='xixixi'),
        ),
    ]
